// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CancelPlaylistDownload(arg1) {
  return window['go']['main']['App']['CancelPlaylistDownload'](arg1);
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetInfo(arg1) {
  return window['go']['main']['App']['GetInfo'](arg1);
}

export function GetPlaylistEntries(arg1) {
  return window['go']['main']['App']['GetPlaylistEntries'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetToolVersions() {
  return window['go']['main']['App']['GetToolVersions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallDependencies() {
  return window['go']['main']['App']['InstallDependencies']();
}

export function OpenInFileManager(arg1) {
  return window['go']['main']['App']['OpenInFileManager'](arg1);
}

export function PickDownloadDir() {
  return window['go']['main']['App']['PickDownloadDir']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchVideos(arg1) {
  return window['go']['main']['App']['SearchVideos'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function StartPlaylistDownload(arg1) {
  return window['go']['main']['App']['StartPlaylistDownload'](arg1);
}
