// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {history} from '../models';
import {types} from '../models';
import {settings} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function CancelPlaylistDownload(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function GetHistory():Promise<Array<history.Entry>>;

export function GetInfo(arg1:string):Promise<types.MediaInfo>;

export function GetPlaylistEntries(arg1:string):Promise<types.PlaylistInfo>;

export function GetSettings():Promise<settings.Data>;

export function GetToolVersions():Promise<types.ToolVersions>;

export function Greet(arg1:string):Promise<string>;

export function OpenInFileManager(arg1:string):Promise<void>;

export function PickDownloadDir():Promise<string>;

export function PickFile():Promise<string>;

export function SaveSettings(arg1:settings.Data):Promise<void>;

export function SearchVideos(arg1:string):Promise<Array<types.SearchResult>>;

export function StartDownload(arg1:types.DownloadRequest):Promise<string>;

export function StartPlaylistDownload(arg1:types.PlaylistDownloadRequest):Promise<string>;
